// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fQu2puVFuVzy8sYaTz_8ICDuAb7xbZA',
    appId: '1:98016014177:web:2f23e22fa8e17380911f20',
    messagingSenderId: '98016014177',
    projectId: 'civix-a4314',
    authDomain: 'civix-a4314.firebaseapp.com',
    storageBucket: 'civix-a4314.firebasestorage.app',
    measurementId: 'G-4XFTPLF0LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccUU3fIqO6aR69LWfBvsp9GZqbirXw2Q',
    appId: '1:98016014177:android:9772ae72927b8e09911f20',
    messagingSenderId: '98016014177',
    projectId: 'civix-a4314',
    storageBucket: 'civix-a4314.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOeToRKXkl0s-80DwTRwDvNDAMX1xHDE',
    appId: '1:98016014177:ios:f33f85df89fb2a25911f20',
    messagingSenderId: '98016014177',
    projectId: 'civix-a4314',
    storageBucket: 'civix-a4314.firebasestorage.app',
    iosBundleId: 'com.example.civixTeams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOeToRKXkl0s-80DwTRwDvNDAMX1xHDE',
    appId: '1:98016014177:ios:f33f85df89fb2a25911f20',
    messagingSenderId: '98016014177',
    projectId: 'civix-a4314',
    storageBucket: 'civix-a4314.firebasestorage.app',
    iosBundleId: 'com.example.civixTeams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-fQu2puVFuVzy8sYaTz_8ICDuAb7xbZA',
    appId: '1:98016014177:web:73036f885217fe3f911f20',
    messagingSenderId: '98016014177',
    projectId: 'civix-a4314',
    authDomain: 'civix-a4314.firebaseapp.com',
    storageBucket: 'civix-a4314.firebasestorage.app',
    measurementId: 'G-ZS8FB0NQL1',
  );
}
